version: '3.3'
services:
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    environment:
      # PGID: '911'
      # PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - $configLocation/lazylibrarian:/config
     - $mediaLocation:/data
    networks:
    #  - media-network
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.lazylibrarian-http.rule: Host(`lazylibrarian.$domainName`)
        traefik.http.services.lazylibrarian.loadbalancer.server.port: '5299'
        traefik.http.routers.lazylibrarian-https.rule: Host(`lazylibrarian.$domainName`)
        traefik.http.routers.lazylibrarian-http.entrypoints: http
        traefik.http.routers.lazylibrarian-https.entrypoints: https
        traefik.http.routers.lazylibrarian-https.tls: 'true'
        traefik.http.routers.lazylibrarian-http.middlewares: https-redirect
        traefik.constraint-label: traefik-public
        traefik.http.routers.lazylibrarian-https.tls.certresolver: le
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        # traefik.http.routers.lazylibrarian-https.middlewares: authelia
      # placement:
      #   constraints:
      #    - node.labels.Arch!=i686
      #    - node.labels.worker==enabled
networks:
  traefik-public:
    external: true