version: '3.3'
services:
  radarr:
    image: lscr.io/linuxserver/radarr:version-5.4.6.8723
    environment:
      # PGID: '911'
      # PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - $configLocation/radarr:/config
     - $mediaLocation:/data
    networks:
    #  - media-network
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.radarr-https.tls: 'true'
        traefik.http.routers.radarr-http.entrypoints: http
        # traefik.http.routers.radarr-https.middlewares: authelia
        traefik.http.routers.radarr-https.tls.certresolver: le
        traefik.http.routers.radarr-https.entrypoints: https
        traefik.http.routers.radarr-http.middlewares: https-redirect
        traefik.constraint-label: traefik-public
        traefik.http.services.radarr.loadbalancer.server.port: '7878'
        traefik.http.routers.radarr-https.rule: Host(`radarr.$domainName`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.radarr-http.rule: Host(`radarr.$domainName`)
      # placement:
      #   constraints:
      #    - node.labels.Arch!=i686
      #    - node.labels.worker==enabled
networks:
  # media-network:
  #   driver: overlay
  traefik-public:
    external: true