version: '3.3'
services:
  homarr:
    image: ghcr.io/ajnart/homarr:0.15.6
    environment:
      # PGID: '911'
      # PUID: '911'
      TZ: Europe/Amsterdam
    volumes:
     - $configLocation/homarr/configs:/app/data/configs
     - $dataLocation/homarr/data:/data
     - $dataLocation/homarr/icons:/app/public/icons
     - $dataLocation/homarr/pics:/app/public/pics
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.homarr-http.rule: Host(`$domainName`)
        traefik.http.routers.homarr-http.entrypoints: http
        traefik.http.routers.homarr-https.tls.certresolver: le
        traefik.http.services.homarr.loadbalancer.server.port: '7575'
        traefik.http.routers.homarr-https.rule: Host(`$domainName`)
        traefik.http.routers.homarr-http.middlewares: https-redirect
        traefik.constraint-label: traefik-public
        traefik.http.routers.homarr-https.tls: 'true'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.homarr-https.entrypoints: https
      # placement:
      #   constraints:
      #    - node.labels.Arch!=i686
      #    - node.labels.worker==enabled
networks:
  traefik-public:
    external: true